version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fipe-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fipe
    ports:
      - "5432:5432"
    volumes:
      - fipe_data:/var/lib/postgresql/data

volumes:
  fipe_data: