app:
    image: python:3.11
    container_name: fipe-app
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fipe
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: sh -c "sleep 5 && pip install pandas psycopg2-binary python-dotenv && python load/carregar.py"