dados_fipe = [
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 36.471,93",
        "Marca": "VW - VolksWagen",
        "Modelo": "GOL 2.0 4x2",
        "AnoModelo": 2017,
        "Combustivel": "Flex",
        "CodigoFipe": "000001-3",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 113.569,99",
        "Marca": "VW - VolksWagen",
        "Modelo": "GOL 1.0 4x2 Aut.",
        "AnoModelo": 2021,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000002-9",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 107.097,59",
        "Marca": "VW - VolksWagen",
        "Modelo": "GOL 2.0 4x2",
        "AnoModelo": 2014,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000003-5",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 293.807,50",
        "Marca": "VW - VolksWagen",
        "Modelo": "GOL 1.0",
        "AnoModelo": 2026,
        "Combustivel": "Diesel",
        "CodigoFipe": "000004-9",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 78.089,50",
        "Marca": "VW - VolksWagen",
        "Modelo": "POLO 2.0 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Diesel",
        "CodigoFipe": "000005-2",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 265.565,18",
        "Marca": "VW - VolksWagen",
        "Modelo": "POLO 1.3 4x4 Aut.",
        "AnoModelo": 2017,
        "Combustivel": "Diesel",
        "CodigoFipe": "000006-0",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 51.793,93",
        "Marca": "VW - VolksWagen",
        "Modelo": "POLO 1.5 4x2 Aut.",
        "AnoModelo": 2023,
        "Combustivel": "Diesel",
        "CodigoFipe": "000007-1",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 313.214,08",
        "Marca": "VW - VolksWagen",
        "Modelo": "POLO 3.0",
        "AnoModelo": 2012,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000008-1",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 97.060,92",
        "Marca": "VW - VolksWagen",
        "Modelo": "AMAROK 3.0 4x2",
        "AnoModelo": 2017,
        "Combustivel": "Diesel",
        "CodigoFipe": "000009-3",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 95.381,46",
        "Marca": "VW - VolksWagen",
        "Modelo": "AMAROK 1.0 4x2",
        "AnoModelo": 2026,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000010-6",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 263.423,16",
        "Marca": "VW - VolksWagen",
        "Modelo": "AMAROK 1.8",
        "AnoModelo": 2010,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000011-8",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 298.462,24",
        "Marca": "VW - VolksWagen",
        "Modelo": "AMAROK 2.0 4x2 Aut.",
        "AnoModelo": 2018,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000012-3",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 26.395,12",
        "Marca": "VW - VolksWagen",
        "Modelo": "VOYAGE 1.0 Aut.",
        "AnoModelo": 2023,
        "Combustivel": "Diesel",
        "CodigoFipe": "000013-3",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 34.776,39",
        "Marca": "VW - VolksWagen",
        "Modelo": "VOYAGE 1.5",
        "AnoModelo": 2026,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000014-9",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 164.084,83",
        "Marca": "VW - VolksWagen",
        "Modelo": "VOYAGE 1.8",
        "AnoModelo": 2016,
        "Combustivel": "Diesel",
        "CodigoFipe": "000015-6",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 215.023,51",
        "Marca": "VW - VolksWagen",
        "Modelo": "VOYAGE 1.5",
        "AnoModelo": 2011,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000016-0",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 40.595,85",
        "Marca": "VW - VolksWagen",
        "Modelo": "SAVEIRO 1.0 4x4",
        "AnoModelo": 2025,
        "Combustivel": "Diesel",
        "CodigoFipe": "000017-2",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 204.325,47",
        "Marca": "VW - VolksWagen",
        "Modelo": "SAVEIRO 1.4 4x4",
        "AnoModelo": 2023,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000018-4",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 344.525,24",
        "Marca": "VW - VolksWagen",
        "Modelo": "SAVEIRO 2.0",
        "AnoModelo": 2015,
        "Combustivel": "Flex",
        "CodigoFipe": "000019-5",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 282.659,45",
        "Marca": "VW - VolksWagen",
        "Modelo": "SAVEIRO 1.8 4x2",
        "AnoModelo": 2024,
        "Combustivel": "Flex",
        "CodigoFipe": "000020-1",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 60.937,73",
        "Marca": "FIAT - Fiat",
        "Modelo": "ARGO 1.6 Aut.",
        "AnoModelo": 2017,
        "Combustivel": "Flex",
        "CodigoFipe": "000021-2",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 181.519,71",
        "Marca": "FIAT - Fiat",
        "Modelo": "ARGO 1.6 4x2 Aut.",
        "AnoModelo": 2013,
        "Combustivel": "Flex",
        "CodigoFipe": "000022-7",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 87.481,41",
        "Marca": "FIAT - Fiat",
        "Modelo": "ARGO 1.8 4x2 Aut.",
        "AnoModelo": 2014,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000023-8",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 66.966,05",
        "Marca": "FIAT - Fiat",
        "Modelo": "ARGO 1.5 4x4 Aut.",
        "AnoModelo": 2026,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000024-1",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 297.208,94",
        "Marca": "FIAT - Fiat",
        "Modelo": "CRONOS 1.5 4x2 Aut.",
        "AnoModelo": 2019,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000025-2",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 312.179,44",
        "Marca": "FIAT - Fiat",
        "Modelo": "CRONOS 2.4 4x4",
        "AnoModelo": 2011,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000026-7",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 41.932,39",
        "Marca": "FIAT - Fiat",
        "Modelo": "CRONOS 4.0 4x2",
        "AnoModelo": 2023,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000027-9",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 233.110,55",
        "Marca": "FIAT - Fiat",
        "Modelo": "CRONOS 2.0 4x2",
        "AnoModelo": 2017,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000028-2",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 203.027,53",
        "Marca": "FIAT - Fiat",
        "Modelo": "STRADA 4.0",
        "AnoModelo": 2018,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000029-0",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 121.896,30",
        "Marca": "FIAT - Fiat",
        "Modelo": "STRADA 1.3 Aut.",
        "AnoModelo": 2012,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000030-3",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 110.018,34",
        "Marca": "FIAT - Fiat",
        "Modelo": "STRADA 4.0 4x2 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Flex",
        "CodigoFipe": "000031-9",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 224.610,69",
        "Marca": "FIAT - Fiat",
        "Modelo": "STRADA 1.3",
        "AnoModelo": 2024,
        "Combustivel": "Flex",
        "CodigoFipe": "000032-3",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 319.621,24",
        "Marca": "FIAT - Fiat",
        "Modelo": "TORO 1.0 4x4",
        "AnoModelo": 2023,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000033-5",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 330.378,80",
        "Marca": "FIAT - Fiat",
        "Modelo": "TORO 1.4 4x2",
        "AnoModelo": 2021,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000034-9",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 310.132,60",
        "Marca": "FIAT - Fiat",
        "Modelo": "TORO 4.0 4x2",
        "AnoModelo": 2025,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000035-8",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 35.504,73",
        "Marca": "FIAT - Fiat",
        "Modelo": "TORO 1.6 4x2",
        "AnoModelo": 2018,
        "Combustivel": "Flex",
        "CodigoFipe": "000036-4",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 30.318,83",
        "Marca": "FIAT - Fiat",
        "Modelo": "PULSE 1.8 4x2",
        "AnoModelo": 2017,
        "Combustivel": "Diesel",
        "CodigoFipe": "000037-8",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 248.503,86",
        "Marca": "FIAT - Fiat",
        "Modelo": "PULSE 1.3 Aut.",
        "AnoModelo": 2012,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000038-5",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 323.870,33",
        "Marca": "FIAT - Fiat",
        "Modelo": "PULSE 3.0 4x2",
        "AnoModelo": 2022,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000039-0",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 265.482,20",
        "Marca": "FIAT - Fiat",
        "Modelo": "PULSE 2.0 Aut.",
        "AnoModelo": 2023,
        "Combustivel": "Diesel",
        "CodigoFipe": "000040-7",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 261.635,82",
        "Marca": "GM - Chevrolet",
        "Modelo": "ONIX 1.8 4x2",
        "AnoModelo": 2014,
        "Combustivel": "Diesel",
        "CodigoFipe": "000041-3",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 129.138,74",
        "Marca": "GM - Chevrolet",
        "Modelo": "ONIX 1.8 4x2",
        "AnoModelo": 2026,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000042-0",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 264.945,28",
        "Marca": "GM - Chevrolet",
        "Modelo": "ONIX 2.4 4x2",
        "AnoModelo": 2013,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000043-6",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 198.449,02",
        "Marca": "GM - Chevrolet",
        "Modelo": "ONIX 2.4 4x4",
        "AnoModelo": 2018,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000044-8",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 236.150,99",
        "Marca": "GM - Chevrolet",
        "Modelo": "TRACKER 1.0 4x2",
        "AnoModelo": 2011,
        "Combustivel": "Diesel",
        "CodigoFipe": "000045-0",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 270.297,98",
        "Marca": "GM - Chevrolet",
        "Modelo": "TRACKER 3.0 4x2",
        "AnoModelo": 2021,
        "Combustivel": "Diesel",
        "CodigoFipe": "000046-7",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 272.389,28",
        "Marca": "GM - Chevrolet",
        "Modelo": "TRACKER 1.5",
        "AnoModelo": 2017,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000047-7",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 42.000,38",
        "Marca": "GM - Chevrolet",
        "Modelo": "TRACKER 1.6 4x4 Aut.",
        "AnoModelo": 2025,
        "Combustivel": "Diesel",
        "CodigoFipe": "000048-6",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 300.544,37",
        "Marca": "GM - Chevrolet",
        "Modelo": "S10 1.3 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Flex",
        "CodigoFipe": "000049-6",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 101.055,80",
        "Marca": "GM - Chevrolet",
        "Modelo": "S10 3.0 4x2",
        "AnoModelo": 2015,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000050-5",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 306.794,74",
        "Marca": "GM - Chevrolet",
        "Modelo": "S10 1.6",
        "AnoModelo": 2012,
        "Combustivel": "Diesel",
        "CodigoFipe": "000051-2",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 53.395,09",
        "Marca": "GM - Chevrolet",
        "Modelo": "S10 1.3",
        "AnoModelo": 2014,
        "Combustivel": "Diesel",
        "CodigoFipe": "000052-5",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 312.557,05",
        "Marca": "GM - Chevrolet",
        "Modelo": "SPIN 1.8 4x2",
        "AnoModelo": 2022,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000053-1",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 278.465,23",
        "Marca": "GM - Chevrolet",
        "Modelo": "SPIN 3.0 4x4 Aut.",
        "AnoModelo": 2023,
        "Combustivel": "Diesel",
        "CodigoFipe": "000054-9",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 199.682,82",
        "Marca": "GM - Chevrolet",
        "Modelo": "SPIN 2.0 4x2",
        "AnoModelo": 2024,
        "Combustivel": "Diesel",
        "CodigoFipe": "000055-9",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 149.704,29",
        "Marca": "GM - Chevrolet",
        "Modelo": "SPIN 4.0 Aut.",
        "AnoModelo": 2020,
        "Combustivel": "Flex",
        "CodigoFipe": "000056-6",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 31.924,64",
        "Marca": "GM - Chevrolet",
        "Modelo": "CRUZE 1.5 4x2",
        "AnoModelo": 2023,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000057-4",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 342.560,76",
        "Marca": "GM - Chevrolet",
        "Modelo": "CRUZE 3.0 Aut.",
        "AnoModelo": 2015,
        "Combustivel": "Diesel",
        "CodigoFipe": "000058-2",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 313.607,78",
        "Marca": "GM - Chevrolet",
        "Modelo": "CRUZE 2.0 Aut.",
        "AnoModelo": 2014,
        "Combustivel": "Flex",
        "CodigoFipe": "000059-0",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 333.479,01",
        "Marca": "GM - Chevrolet",
        "Modelo": "CRUZE 1.4 4x2 Aut.",
        "AnoModelo": 2026,
        "Combustivel": "Diesel",
        "CodigoFipe": "000060-1",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 202.536,09",
        "Marca": "Toyota",
        "Modelo": "COROLLA 2.4 4x4 Aut.",
        "AnoModelo": 2026,
        "Combustivel": "Diesel",
        "CodigoFipe": "000061-1",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 189.400,37",
        "Marca": "Toyota",
        "Modelo": "COROLLA 4.0 4x2 Aut.",
        "AnoModelo": 2013,
        "Combustivel": "Flex",
        "CodigoFipe": "000062-8",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 228.216,77",
        "Marca": "Toyota",
        "Modelo": "COROLLA 1.0 4x2 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Flex",
        "CodigoFipe": "000063-6",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 274.998,57",
        "Marca": "Toyota",
        "Modelo": "COROLLA 2.0 4x4 Aut.",
        "AnoModelo": 2025,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000064-9",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 32.141,93",
        "Marca": "Toyota",
        "Modelo": "HILUX 1.0 4x2",
        "AnoModelo": 2010,
        "Combustivel": "Flex",
        "CodigoFipe": "000065-4",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 101.722,17",
        "Marca": "Toyota",
        "Modelo": "HILUX 4.0 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Flex",
        "CodigoFipe": "000066-0",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 245.165,23",
        "Marca": "Toyota",
        "Modelo": "HILUX 1.5 4x4 Aut.",
        "AnoModelo": 2025,
        "Combustivel": "Flex",
        "CodigoFipe": "000067-2",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 289.165,96",
        "Marca": "Toyota",
        "Modelo": "HILUX 1.0 Aut.",
        "AnoModelo": 2017,
        "Combustivel": "Diesel",
        "CodigoFipe": "000068-8",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 273.471,81",
        "Marca": "Toyota",
        "Modelo": "YARIS 3.0 Aut.",
        "AnoModelo": 2022,
        "Combustivel": "Diesel",
        "CodigoFipe": "000069-8",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 27.578,35",
        "Marca": "Toyota",
        "Modelo": "YARIS 1.6 4x2 Aut.",
        "AnoModelo": 2021,
        "Combustivel": "Diesel",
        "CodigoFipe": "000070-4",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 173.370,45",
        "Marca": "Toyota",
        "Modelo": "YARIS 2.0 4x4",
        "AnoModelo": 2015,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000071-1",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 88.966,40",
        "Marca": "Toyota",
        "Modelo": "YARIS 1.5 Aut.",
        "AnoModelo": 2017,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000072-4",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 208.448,33",
        "Marca": "Toyota",
        "Modelo": "SW4 1.8 4x4 Aut.",
        "AnoModelo": 2020,
        "Combustivel": "Diesel",
        "CodigoFipe": "000073-6",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 63.580,60",
        "Marca": "Toyota",
        "Modelo": "SW4 1.4 Aut.",
        "AnoModelo": 2014,
        "Combustivel": "Flex",
        "CodigoFipe": "000074-7",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 62.956,59",
        "Marca": "Toyota",
        "Modelo": "SW4 1.0 4x2 Aut.",
        "AnoModelo": 2021,
        "Combustivel": "Flex",
        "CodigoFipe": "000075-0",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 84.753,75",
        "Marca": "Toyota",
        "Modelo": "SW4 1.0",
        "AnoModelo": 2011,
        "Combustivel": "Flex",
        "CodigoFipe": "000076-5",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 177.422,93",
        "Marca": "Toyota",
        "Modelo": "RAV4 1.4 4x2 Aut.",
        "AnoModelo": 2017,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000077-2",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 347.409,88",
        "Marca": "Toyota",
        "Modelo": "RAV4 4.0 4x4",
        "AnoModelo": 2020,
        "Combustivel": "Diesel",
        "CodigoFipe": "000078-6",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 105.545,15",
        "Marca": "Toyota",
        "Modelo": "RAV4 2.4 4x4",
        "AnoModelo": 2012,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000079-7",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 232.254,51",
        "Marca": "Toyota",
        "Modelo": "RAV4 3.0 4x2 Aut.",
        "AnoModelo": 2022,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000080-3",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 190.232,10",
        "Marca": "Honda",
        "Modelo": "CIVIC 2.4 4x2 Aut.",
        "AnoModelo": 2017,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000081-0",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 213.568,36",
        "Marca": "Honda",
        "Modelo": "CIVIC 1.8",
        "AnoModelo": 2021,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000082-6",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 131.951,94",
        "Marca": "Honda",
        "Modelo": "CIVIC 3.0 Aut.",
        "AnoModelo": 2026,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000083-3",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 129.059,73",
        "Marca": "Honda",
        "Modelo": "CIVIC 1.3",
        "AnoModelo": 2022,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000084-9",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 132.628,54",
        "Marca": "Honda",
        "Modelo": "HR-V 1.5 4x2",
        "AnoModelo": 2016,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000085-1",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 151.172,25",
        "Marca": "Honda",
        "Modelo": "HR-V 3.0 4x4",
        "AnoModelo": 2011,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000086-7",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 171.749,08",
        "Marca": "Honda",
        "Modelo": "HR-V 2.4 Aut.",
        "AnoModelo": 2026,
        "Combustivel": "Diesel",
        "CodigoFipe": "000087-4",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 28.417,10",
        "Marca": "Honda",
        "Modelo": "HR-V 3.0 4x4",
        "AnoModelo": 2019,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000088-7",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 114.987,65",
        "Marca": "Honda",
        "Modelo": "FIT 1.4 4x4 Aut.",
        "AnoModelo": 2010,
        "Combustivel": "Flex",
        "CodigoFipe": "000089-6",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 287.875,96",
        "Marca": "Honda",
        "Modelo": "FIT 3.0 4x4",
        "AnoModelo": 2016,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000090-5",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 251.444,34",
        "Marca": "Honda",
        "Modelo": "FIT 1.3 4x4",
        "AnoModelo": 2026,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000091-5",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 60.413,15",
        "Marca": "Honda",
        "Modelo": "FIT 1.8 Aut.",
        "AnoModelo": 2025,
        "Combustivel": "Diesel",
        "CodigoFipe": "000092-7",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 321.893,04",
        "Marca": "Honda",
        "Modelo": "CR-V 2.0",
        "AnoModelo": 2025,
        "Combustivel": "Diesel",
        "CodigoFipe": "000093-8",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 128.813,09",
        "Marca": "Honda",
        "Modelo": "CR-V 4.0 4x2 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000094-8",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 53.916,43",
        "Marca": "Honda",
        "Modelo": "CR-V 1.5 4x2 Aut.",
        "AnoModelo": 2018,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000095-7",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 311.711,66",
        "Marca": "Honda",
        "Modelo": "CR-V 1.4",
        "AnoModelo": 2012,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000096-0",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 145.222,43",
        "Marca": "Honda",
        "Modelo": "WR-V 1.5",
        "AnoModelo": 2026,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000097-2",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 232.237,08",
        "Marca": "Honda",
        "Modelo": "WR-V 1.6 4x4",
        "AnoModelo": 2011,
        "Combustivel": "Diesel",
        "CodigoFipe": "000098-4",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 314.312,73",
        "Marca": "Honda",
        "Modelo": "WR-V 1.5 4x4",
        "AnoModelo": 2017,
        "Combustivel": "Flex",
        "CodigoFipe": "000099-5",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 300.987,78",
        "Marca": "Honda",
        "Modelo": "WR-V 4.0 4x4 Aut.",
        "AnoModelo": 2020,
        "Combustivel": "Diesel",
        "CodigoFipe": "000100-3",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 181.737,34",
        "Marca": "Hyundai",
        "Modelo": "HB20 1.8 Aut.",
        "AnoModelo": 2010,
        "Combustivel": "Flex",
        "CodigoFipe": "000101-1",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 336.753,31",
        "Marca": "Hyundai",
        "Modelo": "HB20 3.0 4x2",
        "AnoModelo": 2025,
        "Combustivel": "Diesel",
        "CodigoFipe": "000102-7",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 304.375,12",
        "Marca": "Hyundai",
        "Modelo": "HB20 1.4 Aut.",
        "AnoModelo": 2020,
        "Combustivel": "Flex",
        "CodigoFipe": "000103-9",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 153.259,63",
        "Marca": "Hyundai",
        "Modelo": "HB20 4.0 4x2 Aut.",
        "AnoModelo": 2021,
        "Combustivel": "Diesel",
        "CodigoFipe": "000104-6",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 66.203,69",
        "Marca": "Hyundai",
        "Modelo": "CRETA 1.5 4x4 Aut.",
        "AnoModelo": 2011,
        "Combustivel": "Flex",
        "CodigoFipe": "000105-6",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 163.102,18",
        "Marca": "Hyundai",
        "Modelo": "CRETA 1.0",
        "AnoModelo": 2019,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000106-5",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 328.444,04",
        "Marca": "Hyundai",
        "Modelo": "CRETA 2.4 4x4 Aut.",
        "AnoModelo": 2018,
        "Combustivel": "Diesel",
        "CodigoFipe": "000107-6",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 268.416,17",
        "Marca": "Hyundai",
        "Modelo": "CRETA 4.0 4x2",
        "AnoModelo": 2022,
        "Combustivel": "Flex",
        "CodigoFipe": "000108-8",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 198.391,21",
        "Marca": "Hyundai",
        "Modelo": "TUCSON 1.5 Aut.",
        "AnoModelo": 2023,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000109-3",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 322.344,78",
        "Marca": "Hyundai",
        "Modelo": "TUCSON 1.3",
        "AnoModelo": 2012,
        "Combustivel": "Flex",
        "CodigoFipe": "000110-1",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 129.187,06",
        "Marca": "Hyundai",
        "Modelo": "TUCSON 1.5 4x4 Aut.",
        "AnoModelo": 2021,
        "Combustivel": "Flex",
        "CodigoFipe": "000111-8",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 302.476,93",
        "Marca": "Hyundai",
        "Modelo": "TUCSON 2.0 Aut.",
        "AnoModelo": 2014,
        "Combustivel": "Flex",
        "CodigoFipe": "000112-7",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 288.224,87",
        "Marca": "Hyundai",
        "Modelo": "ELANTRA 1.5 4x4",
        "AnoModelo": 2011,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000113-7",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 282.308,72",
        "Marca": "Hyundai",
        "Modelo": "ELANTRA 1.8 Aut.",
        "AnoModelo": 2022,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000114-5",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 341.650,14",
        "Marca": "Hyundai",
        "Modelo": "ELANTRA 2.0 Aut.",
        "AnoModelo": 2025,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000115-8",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 89.450,45",
        "Marca": "Hyundai",
        "Modelo": "ELANTRA 1.4 4x2 Aut.",
        "AnoModelo": 2015,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000116-8",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 46.771,90",
        "Marca": "Hyundai",
        "Modelo": "SANTA FE 1.5 4x4 Aut.",
        "AnoModelo": 2024,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000117-5",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 78.883,28",
        "Marca": "Hyundai",
        "Modelo": "SANTA FE 1.3 4x2 Aut.",
        "AnoModelo": 2015,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000118-1",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 223.316,83",
        "Marca": "Hyundai",
        "Modelo": "SANTA FE 3.0",
        "AnoModelo": 2011,
        "Combustivel": "Diesel",
        "CodigoFipe": "000119-8",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 178.638,97",
        "Marca": "Hyundai",
        "Modelo": "SANTA FE 1.4 4x2 Aut.",
        "AnoModelo": 2013,
        "Combustivel": "Diesel",
        "CodigoFipe": "000120-5",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 42.517,13",
        "Marca": "Renault",
        "Modelo": "KWID 1.6 4x4 Aut.",
        "AnoModelo": 2015,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000121-1",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 313.434,18",
        "Marca": "Renault",
        "Modelo": "KWID 2.4 4x2",
        "AnoModelo": 2017,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000122-9",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 49.298,19",
        "Marca": "Renault",
        "Modelo": "KWID 4.0 4x4 Aut.",
        "AnoModelo": 2025,
        "Combustivel": "Flex",
        "CodigoFipe": "000123-2",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 333.402,81",
        "Marca": "Renault",
        "Modelo": "KWID 1.4 4x2 Aut.",
        "AnoModelo": 2026,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000124-3",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 344.592,18",
        "Marca": "Renault",
        "Modelo": "SANDERO 3.0 Aut.",
        "AnoModelo": 2018,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000125-9",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 244.070,12",
        "Marca": "Renault",
        "Modelo": "SANDERO 1.5 4x4 Aut.",
        "AnoModelo": 2025,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000126-4",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 56.713,89",
        "Marca": "Renault",
        "Modelo": "SANDERO 1.0 4x4",
        "AnoModelo": 2013,
        "Combustivel": "Flex",
        "CodigoFipe": "000127-2",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 249.048,78",
        "Marca": "Renault",
        "Modelo": "SANDERO 1.3 4x2 Aut.",
        "AnoModelo": 2022,
        "Combustivel": "Diesel",
        "CodigoFipe": "000128-4",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 94.710,66",
        "Marca": "Renault",
        "Modelo": "DUSTER 1.8 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Diesel",
        "CodigoFipe": "000129-6",
        "MesReferencia": "abril de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 262.109,41",
        "Marca": "Renault",
        "Modelo": "DUSTER 1.4 4x4 Aut.",
        "AnoModelo": 2018,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000130-6",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 349.484,86",
        "Marca": "Renault",
        "Modelo": "DUSTER 1.5 4x4",
        "AnoModelo": 2024,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000131-7",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 268.338,24",
        "Marca": "Renault",
        "Modelo": "DUSTER 1.0",
        "AnoModelo": 2025,
        "Combustivel": "Flex",
        "CodigoFipe": "000132-0",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 261.878,60",
        "Marca": "Renault",
        "Modelo": "LOGAN 1.5 Aut.",
        "AnoModelo": 2012,
        "Combustivel": "Diesel",
        "CodigoFipe": "000133-3",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 338.673,61",
        "Marca": "Renault",
        "Modelo": "LOGAN 1.4 4x2",
        "AnoModelo": 2014,
        "Combustivel": "Flex",
        "CodigoFipe": "000134-2",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 299.178,84",
        "Marca": "Renault",
        "Modelo": "LOGAN 2.4 4x2",
        "AnoModelo": 2020,
        "Combustivel": "Diesel",
        "CodigoFipe": "000135-9",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 235.430,27",
        "Marca": "Renault",
        "Modelo": "LOGAN 1.0 4x2 Aut.",
        "AnoModelo": 2018,
        "Combustivel": "Flex",
        "CodigoFipe": "000136-4",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 60.495,53",
        "Marca": "Renault",
        "Modelo": "CAPTUR 1.3 4x4",
        "AnoModelo": 2019,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000137-7",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 305.534,61",
        "Marca": "Renault",
        "Modelo": "CAPTUR 1.0 Aut.",
        "AnoModelo": 2015,
        "Combustivel": "Flex",
        "CodigoFipe": "000138-9",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 293.225,35",
        "Marca": "Renault",
        "Modelo": "CAPTUR 1.8 Aut.",
        "AnoModelo": 2010,
        "Combustivel": "Diesel",
        "CodigoFipe": "000139-5",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 265.194,81",
        "Marca": "Renault",
        "Modelo": "CAPTUR 1.3 Aut.",
        "AnoModelo": 2020,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000140-3",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 168.127,83",
        "Marca": "Ford",
        "Modelo": "KA 2.0 4x2",
        "AnoModelo": 2010,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000141-5",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 114.258,07",
        "Marca": "Ford",
        "Modelo": "KA 1.4",
        "AnoModelo": 2025,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000142-2",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 121.217,62",
        "Marca": "Ford",
        "Modelo": "KA 3.0 4x4 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Flex",
        "CodigoFipe": "000143-7",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 69.847,10",
        "Marca": "Ford",
        "Modelo": "KA 2.4 4x4 Aut.",
        "AnoModelo": 2020,
        "Combustivel": "Diesel",
        "CodigoFipe": "000144-0",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 272.248,47",
        "Marca": "Ford",
        "Modelo": "ECOSPORT 1.0",
        "AnoModelo": 2022,
        "Combustivel": "Diesel",
        "CodigoFipe": "000145-8",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 170.163,63",
        "Marca": "Ford",
        "Modelo": "ECOSPORT 3.0 4x2 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000146-1",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 280.031,92",
        "Marca": "Ford",
        "Modelo": "ECOSPORT 1.8 Aut.",
        "AnoModelo": 2023,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000147-2",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 191.406,08",
        "Marca": "Ford",
        "Modelo": "ECOSPORT 3.0 4x4",
        "AnoModelo": 2019,
        "Combustivel": "Flex",
        "CodigoFipe": "000148-4",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 276.073,89",
        "Marca": "Ford",
        "Modelo": "RANGER 2.4 4x4 Aut.",
        "AnoModelo": 2012,
        "Combustivel": "Flex",
        "CodigoFipe": "000149-0",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 263.396,76",
        "Marca": "Ford",
        "Modelo": "RANGER 1.5 Aut.",
        "AnoModelo": 2022,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000150-9",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 153.961,48",
        "Marca": "Ford",
        "Modelo": "RANGER 1.6 4x4",
        "AnoModelo": 2023,
        "Combustivel": "Flex",
        "CodigoFipe": "000151-3",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 223.372,23",
        "Marca": "Ford",
        "Modelo": "RANGER 1.0",
        "AnoModelo": 2017,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000152-7",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 60.851,24",
        "Marca": "Ford",
        "Modelo": "TERRITORY 1.3 4x4",
        "AnoModelo": 2019,
        "Combustivel": "Flex",
        "CodigoFipe": "000153-4",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 163.081,80",
        "Marca": "Ford",
        "Modelo": "TERRITORY 1.0 4x2 Aut.",
        "AnoModelo": 2026,
        "Combustivel": "Diesel",
        "CodigoFipe": "000154-0",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 254.213,55",
        "Marca": "Ford",
        "Modelo": "TERRITORY 4.0 4x2",
        "AnoModelo": 2014,
        "Combustivel": "Flex",
        "CodigoFipe": "000155-2",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 314.488,89",
        "Marca": "Ford",
        "Modelo": "TERRITORY 4.0 4x4",
        "AnoModelo": 2013,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000156-8",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 155.972,73",
        "Marca": "Ford",
        "Modelo": "BRONCO 2.4 Aut.",
        "AnoModelo": 2011,
        "Combustivel": "Flex",
        "CodigoFipe": "000157-6",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 76.696,93",
        "Marca": "Ford",
        "Modelo": "BRONCO 1.0 4x4",
        "AnoModelo": 2010,
        "Combustivel": "Flex",
        "CodigoFipe": "000158-4",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 309.725,64",
        "Marca": "Ford",
        "Modelo": "BRONCO 2.4",
        "AnoModelo": 2014,
        "Combustivel": "Diesel",
        "CodigoFipe": "000159-0",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 69.149,64",
        "Marca": "Ford",
        "Modelo": "BRONCO 1.8 4x2",
        "AnoModelo": 2022,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000160-1",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 228.084,43",
        "Marca": "Jeep",
        "Modelo": "RENEGADE 2.4 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000161-1",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 158.547,27",
        "Marca": "Jeep",
        "Modelo": "RENEGADE 2.0",
        "AnoModelo": 2021,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000162-6",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 65.802,07",
        "Marca": "Jeep",
        "Modelo": "RENEGADE 2.4",
        "AnoModelo": 2010,
        "Combustivel": "Diesel",
        "CodigoFipe": "000163-0",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 58.491,93",
        "Marca": "Jeep",
        "Modelo": "RENEGADE 1.4 4x2",
        "AnoModelo": 2019,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000164-5",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 79.954,44",
        "Marca": "Jeep",
        "Modelo": "COMPASS 1.0 Aut.",
        "AnoModelo": 2018,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000165-2",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 219.449,03",
        "Marca": "Jeep",
        "Modelo": "COMPASS 1.4",
        "AnoModelo": 2012,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000166-6",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 295.949,00",
        "Marca": "Jeep",
        "Modelo": "COMPASS 4.0 4x2 Aut.",
        "AnoModelo": 2024,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000167-7",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 156.253,70",
        "Marca": "Jeep",
        "Modelo": "COMPASS 2.4",
        "AnoModelo": 2016,
        "Combustivel": "Flex",
        "CodigoFipe": "000168-4",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 238.990,38",
        "Marca": "Jeep",
        "Modelo": "COMMANDER 1.0",
        "AnoModelo": 2013,
        "Combustivel": "Flex",
        "CodigoFipe": "000169-9",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 49.308,76",
        "Marca": "Jeep",
        "Modelo": "COMMANDER 1.8 4x4",
        "AnoModelo": 2021,
        "Combustivel": "Flex",
        "CodigoFipe": "000170-8",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 172.374,86",
        "Marca": "Jeep",
        "Modelo": "COMMANDER 2.0 4x2 Aut.",
        "AnoModelo": 2024,
        "Combustivel": "Flex",
        "CodigoFipe": "000171-0",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 103.483,74",
        "Marca": "Jeep",
        "Modelo": "COMMANDER 2.0 4x4",
        "AnoModelo": 2014,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000172-2",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 285.710,28",
        "Marca": "Jeep",
        "Modelo": "WRANGLER 2.4 4x2 Aut.",
        "AnoModelo": 2023,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000173-1",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 257.487,82",
        "Marca": "Jeep",
        "Modelo": "WRANGLER 1.5 4x4",
        "AnoModelo": 2013,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000174-8",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 316.393,91",
        "Marca": "Jeep",
        "Modelo": "WRANGLER 1.4 4x4 Aut.",
        "AnoModelo": 2010,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000175-0",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 156.738,30",
        "Marca": "Jeep",
        "Modelo": "WRANGLER 4.0 4x4",
        "AnoModelo": 2024,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000176-5",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 277.181,58",
        "Marca": "Jeep",
        "Modelo": "GLADIATOR 2.0 4x4 Aut.",
        "AnoModelo": 2016,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000177-8",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 335.047,31",
        "Marca": "Jeep",
        "Modelo": "GLADIATOR 4.0 4x4",
        "AnoModelo": 2010,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000178-7",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 58.814,71",
        "Marca": "Jeep",
        "Modelo": "GLADIATOR 2.4",
        "AnoModelo": 2015,
        "Combustivel": "Flex",
        "CodigoFipe": "000179-5",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 33.258,56",
        "Marca": "Jeep",
        "Modelo": "GLADIATOR 4.0 4x4 Aut.",
        "AnoModelo": 2012,
        "Combustivel": "Diesel",
        "CodigoFipe": "000180-8",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 323.509,65",
        "Marca": "Nissan",
        "Modelo": "KICKS 1.5 4x2",
        "AnoModelo": 2012,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000181-1",
        "MesReferencia": "setembro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 97.665,94",
        "Marca": "Nissan",
        "Modelo": "KICKS 1.8 4x4 Aut.",
        "AnoModelo": 2015,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000182-2",
        "MesReferencia": "julho de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 135.258,59",
        "Marca": "Nissan",
        "Modelo": "KICKS 1.5 4x2 Aut.",
        "AnoModelo": 2010,
        "Combustivel": "Diesel",
        "CodigoFipe": "000183-4",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 121.072,37",
        "Marca": "Nissan",
        "Modelo": "KICKS 1.3",
        "AnoModelo": 2022,
        "Combustivel": "Diesel",
        "CodigoFipe": "000184-3",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 164.117,47",
        "Marca": "Nissan",
        "Modelo": "FRONTIER 1.5 4x2",
        "AnoModelo": 2014,
        "Combustivel": "Flex",
        "CodigoFipe": "000185-7",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 244.487,61",
        "Marca": "Nissan",
        "Modelo": "FRONTIER 4.0 4x2",
        "AnoModelo": 2018,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000186-5",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 281.982,75",
        "Marca": "Nissan",
        "Modelo": "FRONTIER 1.6 4x4 Aut.",
        "AnoModelo": 2021,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000187-8",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 146.493,32",
        "Marca": "Nissan",
        "Modelo": "FRONTIER 2.0 4x2 Aut.",
        "AnoModelo": 2013,
        "Combustivel": "Flex",
        "CodigoFipe": "000188-1",
        "MesReferencia": "maio de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 247.467,65",
        "Marca": "Nissan",
        "Modelo": "VERSA 1.8 4x2 Aut.",
        "AnoModelo": 2011,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000189-0",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 34.249,65",
        "Marca": "Nissan",
        "Modelo": "VERSA 1.8",
        "AnoModelo": 2016,
        "Combustivel": "Flex",
        "CodigoFipe": "000190-7",
        "MesReferencia": "março de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 44.298,67",
        "Marca": "Nissan",
        "Modelo": "VERSA 1.4",
        "AnoModelo": 2020,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000191-8",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "G"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 136.302,45",
        "Marca": "Nissan",
        "Modelo": "VERSA 1.8",
        "AnoModelo": 2021,
        "Combustivel": "Diesel",
        "CodigoFipe": "000192-8",
        "MesReferencia": "junho de 2026",
        "SiglaCombustivel": "D"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 230.453,86",
        "Marca": "Nissan",
        "Modelo": "MARCH 1.5 Aut.",
        "AnoModelo": 2024,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000193-1",
        "MesReferencia": "novembro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 81.524,94",
        "Marca": "Nissan",
        "Modelo": "MARCH 1.4 4x4",
        "AnoModelo": 2017,
        "Combustivel": "Flex",
        "CodigoFipe": "000194-5",
        "MesReferencia": "janeiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 349.020,52",
        "Marca": "Nissan",
        "Modelo": "MARCH 3.0 4x2",
        "AnoModelo": 2022,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000195-5",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 95.407,14",
        "Marca": "Nissan",
        "Modelo": "MARCH 1.5 4x4 Aut.",
        "AnoModelo": 2010,
        "Combustivel": "Flex",
        "CodigoFipe": "000196-5",
        "MesReferencia": "dezembro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 215.725,96",
        "Marca": "Nissan",
        "Modelo": "SENTRA 1.8 4x2",
        "AnoModelo": 2018,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000197-4",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 187.154,27",
        "Marca": "Nissan",
        "Modelo": "SENTRA 4.0 4x4",
        "AnoModelo": 2017,
        "Combustivel": "Eletrico",
        "CodigoFipe": "000198-4",
        "MesReferencia": "agosto de 2026",
        "SiglaCombustivel": "E"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 100.147,64",
        "Marca": "Nissan",
        "Modelo": "SENTRA 4.0 4x2",
        "AnoModelo": 2022,
        "Combustivel": "Flex",
        "CodigoFipe": "000199-0",
        "MesReferencia": "fevereiro de 2026",
        "SiglaCombustivel": "F"
    },
    {
        "TipoVeiculo": 1,
        "Valor": "R$ 260.625,14",
        "Marca": "Nissan",
        "Modelo": "SENTRA 1.6 4x2",
        "AnoModelo": 2012,
        "Combustivel": "Gasolina",
        "CodigoFipe": "000200-8",
        "MesReferencia": "outubro de 2026",
        "SiglaCombustivel": "G"
    }
]